spring:
  application:
    name: spring_shield
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/bd_shield?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update